CREATE TABLE equipment (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    serial_number TEXT UNIQUE NOT NULL,
    department TEXT NOT NULL,
    team TEXT NOT NULL,
    purchase_date DATE NOT NULL,
    warranty_years INTEGER NOT NULL,
    warranty_status TEXT NOT NULL,
    health TEXT NOT NULL
);

INSERT INTO equipment (name, serial_number, department, team, purchase_date, warranty_years, warranty_status, health) VALUES
('Laptop Dell XPS 15', 'DL-XPS-001', 'IT Department', 'IT Team 1', '2023-06-15', 5, 'Under Warranty', 'Good'),
('Laptop HP ProBook 450', 'HP-PRO-002', 'IT Department', 'IT Team 1', '2023-09-20', 5, 'Under Warranty', 'Good'),
('Desktop Computer Lenovo', 'LN-DSK-003', 'IT Department', 'IT Team 2', '2021-03-10', 5, 'Warranty Expired', 'Medium'),
('Desktop Computer HP', 'HP-DSK-004', 'IT Department', 'IT Team 2', '2019-08-22', 5, 'Warranty Expired', 'Low'),
('Wireless Mouse Logitech', 'LG-MUS-005', 'IT Department', 'IT Team 1', '2024-01-12', 2, 'Under Warranty', 'Good'),
('Wireless Keyboard Logitech', 'LG-KEY-006', 'IT Department', 'IT Team 1', '2024-02-05', 2, 'Under Warranty', 'Good'),
('Monitor Dell 27inch', 'DL-MON-007', 'IT Department', 'IT Team 2', '2022-11-18', 5, 'Under Warranty', 'Good'),
('Monitor LG 24inch', 'LG-MON-008', 'IT Department', 'IT Team 2', '2020-07-30', 5, 'Warranty Expired', 'Medium'),
('Printer HP LaserJet M404', 'HP-PRT-009', 'IT Department', 'IT Team 3', '2018-12-10', 5, 'Warranty Expired', 'Low'),
('Network Printer Canon', 'CN-NPT-010', 'IT Department', 'IT Team 3', '2023-05-17', 5, 'Under Warranty', 'Good'),
('Server IBM Power System', 'IBM-SRV-011', 'IT Department', 'IT Team 4', '2022-02-28', 5, 'Under Warranty', 'Good'),
('Backup Storage Dell PowerVault', 'DL-BAK-012', 'IT Department', 'IT Team 4', '2021-09-12', 5, 'Under Warranty', 'Good'),
('Network Router Cisco ASR', 'CSC-RTR-013', 'Network & Security', 'Network Support Team', '2023-08-25', 5, 'Under Warranty', 'Good'),
('Network Switch Juniper EX', 'JNP-SWT-014', 'Network & Security', 'Network Support Team', '2022-04-18', 5, 'Under Warranty', 'Good'),
('Firewall Palo Alto Networks', 'PAN-FWL-015', 'Network & Security', 'Network Support Team', '2020-11-30', 5, 'Warranty Expired', 'Medium'),
('Wireless Access Point Ubiquiti', 'UBT-WAP-016', 'Network & Security', 'Network Support Team', '2024-03-22', 3, 'Under Warranty', 'Good'),
('Network Firewall FortiGate', 'FTG-FWL-017', 'Network & Security', 'Network Support Team', '2019-06-14', 5, 'Warranty Expired', 'Low'),
('Projector Epson EB-2250U', 'EPS-PRJ-018', 'Administration', 'Office Equipment Team', '2023-01-10', 5, 'Under Warranty', 'Good'),
('Biometric Attendance ZKTeco', 'ZKT-BIO-019', 'Administration', 'Office Equipment Team', '2021-07-20', 5, 'Under Warranty', 'Good'),
('Document Scanner Fujitsu', 'FJS-SCN-020', 'Administration', 'Office Equipment Team', '2020-05-15', 5, 'Warranty Expired', 'Medium'),
('Conference Phone Polycom', 'PLY-PHN-021', 'Administration', 'Office Equipment Team', '2022-09-08', 3, 'Under Warranty', 'Good'),
('CCTV Camera System Hikvision', 'HKV-CCV-022', 'Security Department', 'Security Ops Team', '2023-04-12', 5, 'Under Warranty', 'Good'),
('Security Gate Access Control', 'SGC-ACC-023', 'Security Department', 'Security Ops Team', '2021-11-25', 5, 'Under Warranty', 'Good'),
('Alarm System Bosch', 'BSC-ALM-024', 'Security Department', 'Security Ops Team', '2019-02-18', 5, 'Warranty Expired', 'Low'),
('CNC Machine Haas VF4', 'HAS-CNC-025', 'Production Department', 'Production Maintenance Team', '2023-10-30', 7, 'Under Warranty', 'Good'),
('Conveyor Belt System Siemens', 'SIM-CVY-026', 'Production Department', 'Production Maintenance Team', '2020-08-14', 7, 'Warranty Expired', 'Medium'),
('Hydraulic Press Enerpac', 'ENP-HYD-027', 'Production Department', 'Production Maintenance Team', '2018-03-22', 7, 'Warranty Expired', 'Low'),
('Packaging Machine Bosch Rexroth', 'BRX-PKG-028', 'Production Department', 'Production Maintenance Team', '2022-12-10', 7, 'Under Warranty', 'Good'),
('Industrial Robot ABB IRB1200', 'ABB-RBT-029', 'Production Department', 'Production Maintenance Team', '2024-01-05', 7, 'Under Warranty', 'Good'),
('Welding Machine Lincoln Electric', 'LEC-WLD-030', 'Production Department', 'Production Maintenance Team', '2019-09-17', 7, 'Warranty Expired', 'Low'),
('Forklift Machine Toyota 8FDU25', 'TYT-FRK-031', 'Logistics', 'Logistics Maintenance Team', '2021-05-20', 5, 'Under Warranty', 'Good'),
('Company Transport Vehicle Tata Nexon', 'TTA-VHC-032', 'Logistics', 'Logistics Maintenance Team', '2023-02-14', 5, 'Under Warranty', 'Good'),
('Delivery Van Maruti Eeco', 'MRT-VAN-033', 'Logistics', 'Logistics Maintenance Team', '2020-06-10', 5, 'Warranty Expired', 'Medium'),
('ECG Machine GE MAC 400', 'GEM-ECG-034', 'Medical Department', 'Medical Equipment Team', '2022-07-19', 5, 'Under Warranty', 'Good'),
('Ventilator Philips Respironics', 'PLR-VNT-035', 'Medical Department', 'Medical Equipment Team', '2021-10-25', 5, 'Under Warranty', 'Good'),
('Ultrasound Machine Siemens Acuson', 'SIM-ULT-036', 'Medical Department', 'Medical Equipment Team', '2019-12-08', 5, 'Warranty Expired', 'Low');
